name: Deploy Runner

on:
  push:
    branches:
      - master

jobs:
  Deploy-MSCV:
    name: "Deploy Intervaltimer for Windows"
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.1'

      - name: Install Tools Ninja and mvsc
        uses: ilammy/msvc-dev-cmd@v1
      - uses: seanmiddleditch/gha-setup-ninja@master
      
      - name: build 
        shell: pwsh 
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build . --target all
          cd ..
          mkdir deploy 
          cd deploy
          Copy-Item "../build/src/IntervaltimerApplication.exe" -Destination "./IntervaltimerApplication.exe"
          $deploy_exe = "${Env:Qt6_DIR}" + "/bin/windeployqt.exe"
          & $deploy_exe --dir . --qmldir ../build ../build/src/IntervaltimerApplication.exe

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/upload-artifact@v2
        with:
          name: Intervaltimer-${{ steps.extract_branch.outputs.branch }}-windows-x86.zip
          path: deploy

  Deploy-Android:
    name: "Deploy Intervaltimer for Android"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: mkdir 
        run: mkdir ${GITHUB_WORKSPACE}/build

      - name: Build
        run: >-
          docker run --rm 
          -v ${GITHUB_WORKSPACE}:/project 
          -v ${GITHUB_WORKSPACE}/build:/build
          ghcr.io/fettpet/docker_qt_android:qt6.2.2-android_sdk7583922
          -DCMAKE_BUILD_TYPE=Release

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/upload-artifact@v2
        with:
          name: Intervaltimer-${{ steps.extract_branch.outputs.branch }}-android.apk
          path: build/src/android-build/build/outputs/apk/debug/android-build-debug.apk